#!/bin/sh

npm run lint
if [ $? = 0 ]; then
    printf "\n\n\n ----------------- Remember to fix any existing warnings ----------------- \n\n\n\n"
    elif [ $? = 1 ]; then
    printf "\n\n\n ----------------- Fix all the linting errors before commiting ----------------- \n\n\n\n"
    exit 0
fi
