#!/bin/sh

npm run lint
if [ $? = 0 ]; then
    printf "\n\n\n ----------------- Remember to fix any existing warnings ----------------- \n\n\n\n"
    elif [ $? = 1 ]; then
    printf "\n\n\n ----------------- Fix all the linting errors before commiting ----------------- \n\n\n\n"
    exit 0
fi

npm run test:server:pc
if [ $? = 0 ]; then
    printf "\n\n\n ----------------- All server tests passed ----------------- \n\n\n\n"
    elif [ $? = 1 ]; then
    printf "\n\n\n ----------------- Fix all the non passing tests before commiting ----------------- \n\n\n\n"
    exit 0
fi
